modLoader="javafml"
loaderVersion="[11,)"
license="MIT"

[[mods]]
modId="magic_carpet"
version="${mod_version}"
displayName="MagicCarpet"
description='''Adds Magic Carpets to Minecraft.'''
authors="brainage04"
displayURL="https://github.com/brainage04/MagicCarpet"
logoFile="assets/magic_carpet/icon.png"

[[mixins]]
config="magic_carpet.mixins.json"

[[dependencies.magic_carpet]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.magic_carpet]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},)"
ordering="NONE"
side="BOTH"
